theme: jekyll-theme-dinky
title: gipsi.github.io <a href="https://internetdefenseleague.org"><img src="https://internetdefenseleague.org/images/badges/final/side_bar_badge.png" alt="Member of The Internet Defense League"/></a>
description: 100DaysOfCode 2018  
