theme: jekyll-theme-dinky
sticker: <a href="https://internetdefenseleague.org"><img src="https://internetdefenseleague.org/images/badges/final/side_bar_badge.png" alt="Member of The Internet Defense League"/></a>
title: Gipsi tana 
description: 100DaysOfCode 2018  
